### ISSUE TITLE
Wrong config given & URL not working anymore

### ISSUE THREAD

**Issue by azro352** [mykle1/MMM-EARTH-Live#1]
The 2 following config given are wrong : 

- `disabled: f` should be `disabled: false`
- `module: 'MMM-EARTH-Live'` should be `module: 'MMM-ISS-Live'`

---------

The autoplay seems to have problem as the video does not run auto on the MM

**Comment by mykle1** [comment]
disabled: f is now disabled: false

MMM-EARTH-Live and MMM-ISS-Live are two seperate modules with different url's. Sometimes the feeds are down. There is nothing I can do about that. Be patient. They come back. It usually only takes a few minutes. I loaded MMM-EARTH-Live and it was down but came back up in 5 minutes. This will not always be the case but it does happen.

The readme now contains the fix for the autoplay issue. It's a problem with Electron, not the module. The fix is easy and it does work
